### ISSUE TITLE
bug with vite 3.1.5

### ISSUE THREAD

**Issue by reslear** [ikenfin/vite-plugin-sentry#117]
<img width="673" alt="Screenshot 2022-10-06 at 13 35 32" src="https://user-images.githubusercontent.com/12596485/194302614-e6339c87-880f-4d40-9d6a-731d7d4ddc64.png">

**Comment by ikenfin** [comment]
Hi! Seems provided es plugin version is broken, i will check this one

**Comment by ikenfin** [comment]
@reslear Can you please also provide your vite.config.ts?

**Comment by ikenfin** [comment]
Thanks!

Seems it's fixed now. Just published new 1.1.6 version which now is supporting both commonjs and modern modules 👍

**Comment by reslear** [comment]
thank you 🔥
