### ISSUE TITLE
How could I set `--ignore-missing` option to this plugin?

### ISSUE THREAD

**Issue by IkumaTadokoro** [ikenfin/vite-plugin-sentry#130]
Hello. We are using Vite in our project, and this plugin is handy and helpful.

I have a question. Sometimes, when we specify `auto` for the `setCommit` option, we get an error on the sentry-cli because the SHA of the previous release is not found.

```
> Found 2 release files
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: my-org
> Project: my-project
> Release: 9j6ae7f31bc09a556158eecfdsb28d58rtbg8db73
> Dist: None

Source Map Upload Report
  Minified Scripts
    ~/assets/index.2fcf2f3d.js (sourcemap at index.2fcf2f3d.js.map)
  Source Maps
    ~/assets/index.2fcf2f3d.js.map
[plugin:sentry] Error while uploading sourcemaps to Sentry: Command failed: my-project/node_modules/@sentry/cli/sentry-cli releases set-commits 9j6ae7f31bc09a556158eecfdsb28d58rtbg8db73 —auto
error: Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means that the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

As shown in the error log, I can avoid the error by using `-ignore-missing`, but as far as I have confirmed, I am aware that I cannot specify this option unless you run sentry-cli directly.

However, I would be pleased if somehow I could specify `-ignore-missing` in the settings of this plugin, as I would like to create releases automatically in the CI/CD pipeline. I would like to know if there is any way or configuration to set this up 🙏.

**Comment by ikenfin** [comment]
Hi! I had updated the readme section about `ignoreMissing` and `ignoreEmpty` settings, so closing this one. Thanks for pointing me on that!

**Comment by IkumaTadokoro** [comment]
Thanks for your kind instruction!
I achieved what I wanted to do with the options you gave me, and thank you for the addition to the README. I think it will be beneficial to others who use the plugin.
