### ISSUE TITLE
Plugin runs twice when building with SSR

### ISSUE THREAD

**Issue by patryk-smc** [ikenfin/vite-plugin-sentry#16]
Hey,
thank you for building this plugin. It was quite a time saver for us.

I have noticed that when we build our app, this plugin seems to be running twice. 

We have been using the typical command for building SSR apps with Vite: `vite build && vite build --ssr` so it kinda made sense for me why it runs twice. I thought that if I split our config into two: one for client build (with Sentry plugin) and another one for SSR build (without Sentry plugin), this problem would go away. 

So I created two configs and run the command: `vite build --config vite.config.client.ts && vite build --ssr --config vite.config.server.ts`

The weird thing is that Sentry plugin still runs twice. What's even weirder is the fact that it doesn't run after it's done with first build. It is running twice, simultaneously when it's done with SSR build. 

Just to be sure, I created a tiny plugin that all it does is console.log and I added it to the `vite.config.client.ts`. And it logs just after the client build is done. That's how I came to the conclusion that something might not be right with the vite-plugin-sentry. 

<img width="904" alt="CleanShot 2022-06-24 at 20 30 49@2x" src="https://user-images.githubusercontent.com/37963339/175644296-88d1ea5c-1e05-4566-b97b-0fabadf90bef.png">

**Comment by ikenfin** [comment]
Hi! Thanks for issue and PR. Can you please review my comment at your code and apply small fix?

**Comment by patryk-smc** [comment]
@ikenfin You're welcome! I don't see your comment though.

**Comment by ikenfin** [comment]
@patryk-smc oh, sorry, i did'nt complete review process. Requested changes, so now you can see it here https://github.com/ikenfin/vite-plugin-sentry/pull/17

**Comment by ikenfin** [comment]
Thanks alot! 
Merged in master, i will publish new version in about of 5-10mins
