### ISSUE TITLE
Enable sentry in non-production builds

### ISSUE THREAD

**Issue by atrakh** [ikenfin/vite-plugin-sentry#2]
Hi! Thanks for building this plugin. Wondering if it would be possible to add an option to enable Sentry for non-production builds?

**Comment by ikenfin** [comment]
@atrakh hi! 

Yes, i can add something like `forceEnabled` into plugin options, but why would you need such feature?

**Comment by atrakh** [comment]
Hey @ikenfin -- apologies the notifications for this issue totally fell off my radar. I believe the original goal here was to debug the sentry integration locally in a development build before releasing it to a live environment.

**Comment by ikenfin** [comment]
@atrakh ok i got your point. I think i will add new option to allow users to decide when sentry data will be published, because it really can be handy for staging or public test releases.

**Comment by ikenfin** [comment]
@atrakh hi! Added the `skipEnvironmentCheck` option in v1.0.12, so now you can use plugin in environments other than production 👍
