### ISSUE TITLE
How to set `dist`

### ISSUE THREAD

**Issue by OrbisK** [ikenfin/vite-plugin-sentry#20]
![image](https://user-images.githubusercontent.com/37191683/177103872-906de835-a355-4724-9b7b-573a24f1415d.png)

Currently I am missing the ability to set the dist: https://docs.sentry.io/product/cli/releases/#sentry-cli-sourcemaps (see option `--dist`)

**Comment by ikenfin** [comment]
@OrbisK hi! I will look to add this option to plugin asap!

**Comment by ikenfin** [comment]
Seems you can use `dist` already (_place it at sourceMaps config object_). 

I think sentry team accidentialy placed `dist` option to the top level, while this is source map uploader option (https://github.com/getsentry/sentry-cli/blob/master/js/releases/options/uploadSourcemaps.js#L10). 

I have published patched types in git repo, also will make PR to sentry-cli

**Comment by OrbisK** [comment]
Just for reference: https://github.com/getsentry/sentry-cli/pull/1269

**Comment by ikenfin** [comment]
Sentry/cli released new version fixing the issue, i've just published v1.1.1 that uses updated types👍
