### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by rudolfbyker** [ikenfin/vite-plugin-sentry#261]
Nice plugin. Thanks.

One of the things that the docs for this plugin (and https://github.com/getsentry/sentry-webpack-plugin ) should mention, but do not, is the purpose of this plugin. New users tend to get confused between creating releases and uploading source maps on the one hand (which is what this plugin does) and reporting errors and performance (which is NOT what this plugin does). I think this should be made clear in the README.

Something like this:

```
This plugin hooks into the Vite build step, to create a new release and upload source maps. It does not instrument error reporting in your app.
```

**Comment by ikenfin** [comment]
Hi @rudolfbyker!
Good point, i will add this info to readme, thanks!

**Comment by ikenfin** [comment]
I think we can update Readme heading like shown below, wdyt?

# Plugin for Vite ⚡️ to create releases and upload sourcemaps to Sentry

![Version](https://img.shields.io/npm/v/vite-plugin-sentry)[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](#)[![codecov](https://codecov.io/gh/ikenfin/vite-plugin-sentry/branch/master/graph/badge.svg?token=RAM0TAVIIQ)](https://codecov.io/gh/ikenfin/vite-plugin-sentry)

> This plugin hooks into the Vite build step, to create a new release and upload source maps. It does not instrument error reporting in your app.

**Comment by rudolfbyker** [comment]
Very nice

**Comment by ikenfin** [comment]
Okay, fixed. Thanks!
