### ISSUE TITLE
After release of vite 3.0, will you support it ? 

### ISSUE THREAD

**Issue by imvkmark** [ikenfin/vite-plugin-sentry#34]
vite has release of 3.0

https://cn.vitejs.dev/guide/migration.html#advanced

**Comment by albohlabs** [comment]
I've tested locally with vite v3 and everything looks fine. Maybe somebody else can test with v3 too and afterwards we can merge https://github.com/ikenfin/vite-plugin-sentry/pull/35

**Comment by ikenfin** [comment]
@imvkmark Yeah, it seems that vite 3 at the moment don't have any breaking changes affecting this plugin in any way. If they will release something breaking i'll upgrade plugin.

@albohlabs Thanks! I will test vite3 too, when my laptop arrives from repair shop

**Comment by ikenfin** [comment]
For now tested with vite 3.0.0 and 3.0.1 - it works without any causes. I will publish new version today with version fixes from #35  Closing for now, thanks 👍
