### ISSUE TITLE
if i use vue2 with vite, can this plugin work?

### ISSUE THREAD

**Issue by weirui88888** [ikenfin/vite-plugin-sentry#4]

**Comment by ikenfin** [comment]
> > Hi @weirui88888 ! Theoretically you can use this plugin with any library or vanilla based project, because there is no any dependency on user code. I've checked plugin with vue2 project - it works without any problems 👍
> 
> I am frustrated, everything is configured according to the documentation。but it seems that the located source file is always wrong。😫

Can you please provide some context? What you already did, maybe part of configs?
 
There are multiple situations when sentry will not load/use source maps, for example when the app is not in public url (you can use ngrok/localtunnel in that situations), or there can be wrong `urlPrefix`.

**Comment by weirui88888** [comment]
> Oh and i totally forgot - try to upgrade to latest version, i've sent updates to npm about 3hrs ago. Latest plugin version contains updated @sentry/cli package! 👍

I will try one by one ，Thank you so much for your help。

When I succeed, I will be the first to notify you。:smile:

**Comment by weirui88888** [comment]
Still there? In order to maintain a similar configuration with you, I created a demo project with vite, which uses vue2. Why can't I locate it accurately? I'll find a way for you to try to see my demo. :punch:
