### ISSUE TITLE
FYI, the README is gone from the npm page

### ISSUE THREAD

**Issue by hangtwenty** [ikenfin/vite-plugin-sentry#52]
https://www.npmjs.com/package/vite-plugin-sentry

![image](https://user-images.githubusercontent.com/2420688/182216586-5e608db4-bf7a-497c-88b0-b5ee741bc0cb.png)

Seems like something from the last release, as it was there are few days ago!

**Comment by ikenfin** [comment]
@hangtwenty hi! 
In my case it seems to be okay. Maybe was an npm bug?

![image](https://user-images.githubusercontent.com/1705564/182218597-7b385ebd-bb58-46f8-a11e-3160302385ac.png)
