### ISSUE TITLE
an error occurred when using "npm i vite-plugin-sentry"

### ISSUE THREAD

**Issue by nikojxie** [ikenfin/vite-plugin-sentry#8]
npm ERR! code 1
npm ERR! path C:\workspace\demo\node_modules\@sentry\cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! info sentry-cli Using cached binary: C:\Users\admin\AppData\Local\npm-cache\sentry-cli\5c4041-sentry-cli-Windows-x86-64.exe
npm ERR! Error: Command failed: C:\workspace\demo\node_modules\@sentry\cli\sentry-cli.exe --version

node version:16.13.0
Windows10

Is there something wrong with my use? Thanks

**Comment by ikenfin** [comment]
Hi! It seems that path to node_modules is incorrect - missing slash netween node_modules and @sentry.

‘C:\workspace\demo\node_modules@sentry\cli’

Do you have similar problems while install other packages?

**Comment by nikojxie** [comment]
no，It is correct when installing other packages, like @sentry/tracing and @sentry/vue

**Comment by ikenfin** [comment]
Strange, i will try to test this behavior on windows by myself in next couple of days, maybe there is a some windows specific bug with sentry cli. Which node version you use?

**Comment by nikojxie** [comment]
i think so too,  my node version is 16.13.0,  thanks for your help

**Comment by ikenfin** [comment]
Hi @nikojxie !

I've found solution for this issue, it comes from sentry-cli tool which is used to interact with sentry. This binary requires vc redist package to be installed, so you need to install Microsoft VC Redistributable before trying to use this plugin.

You can download MS Redist installation package on Microsoft website - https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by nikojxie** [comment]
Hi@ikenfin!
thank you for your reply, it worked for me.

**Comment by ikenfin** [comment]
Glad to hear that! 👍
