### ISSUE TITLE
Failed to resolve import "virtual:vite-plugin-sentry/sentry-release" from "src/main.tsx". Does the file exist?

### ISSUE THREAD

**Issue by mattoni** [ikenfin/vite-plugin-sentry#81]
![image](https://user-images.githubusercontent.com/5110855/186544526-6c24d9af-915b-40a5-9a33-906c35030c7f.png)

I am using version `1.1.5` and getting this error. My import is in main.tsx:

![image](https://user-images.githubusercontent.com/5110855/186544632-4f5f69e0-7db8-4def-b49a-6f57535f9e65.png)

**Comment by ikenfin** [comment]
@mattoni Hi! Virtual module `sentry-release` was deprecated from v1.1.1 and removed in v1.1.5. You already trying to use new import.meta fields, but did'nt replaced virtual module import path with `virtual:vite-plugin-sentry/sentry-config`
