### ISSUE TITLE
ViteSentryPluginOptions requires deploy, although the implementation does not

### ISSUE THREAD

**Issue by pmk1c** [ikenfin/vite-plugin-sentry#9]
We do not want to create a Sentry deployment when building with Vite, because at the time the build is done we do not know whether it will be deployed as `staging` or `production` environment.

The type `ViteSentryPluginOptions` enforces us to set `deploy` and `deploy.env`, but the code seems smart enough to skip creating a deployment when the options are not given (see: https://github.com/ikenfin/vite-plugin-sentry/blob/master/src/index.ts#L99). Therefore setting `deploy` should not be enforced in my opinion.

Looking at the code, we set `deploy.env` to an empty string, which should skip creating a deployment in Sentry.

**Comment by pmk1c** [comment]
Besides that, not using `setCommit` is also a bit weird, since you need to set:

```
setCommit: {}
```

**Comment by ikenfin** [comment]
Hi @pmk1c !
Seems reasonable, i will update the typings, thanks!👍

**Comment by ikenfin** [comment]
Hi @pmk1c 
In latest update i've made most settings optional. The only required field in config now is `sourceMaps` field
